name: CI on multiple events
on:
  push:
    branches:
          - main
  pull_request:
     branches:
          - main
  release:
      types: [published,created]
jobs:
    build-and-test:
         runs-on: ubuntu-latest
         steps:
           - uses: actions/checkout@v2
           - name: set up python
