name: CI on multiple events
on:
  push:
    branches:
          - main
  pull_request:
     branches:
          - main
  release:
      types: [published,created]
jobs:
    build-and-test:
         runs-on: ubuntu-latest
         steps:
           - uses: actions/checkout@v4
           - name: Set up JDK 11 for x64
             uses: actions/setup-java@v4
             with:
               java-version: '11'
               distribution: 'temurin'
               architecture: x64

